#!/bin/bash

# Foliage. An Ancestral Recombination Graph Manipulation Library.
# 
# Copyright (c) 2008 Genome Research Ltd.
# 
# Author: Lior Galanti <lior.galanti@gmail.com>
# 
# This file is part of Foliage.
# Foliage is free software; you can redistribute it and/or modify it under the terms of 
# the GNU General Public License as published by the Free Software Foundation; 
# either version 2 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
# 


# -----------------------------------------------------------------------------------------
# bash wrapper script for running foliage.
# Memory allocation for the JVM can be adjusted with -Xmx for maximum and -Xmn for minimum.		
# Requires JVM 6.x
# -----------------------------------------------------------------------------------------

JAVA="/software/jdk1.6.0_01/bin/java"
ARGMLLIB="/nfs/phd/lg8/workspace/argml/argmllib.jar"
FOLIAGE=$JAVA' -Djava.awt.headless=true -Xmx1000M -Xmn1000M -jar '$ARGMLLIB

$FOLIAGE $*
